"""Generates a synthetic demo case-export folder at sample_case/, matching the
folder format app/services/ingestion.py:CaseFolderParser expects.

This creates believable contacts/calls/messages/device_events data (including
a deliberately-planted anomaly: a briefly-installed app and a message from an
odd hour) so the demo has something to show without needing real evidence.

It CANNOT create real face photos or audio recordings — there's no image/audio
generation tool in this environment. Drop your own .jpg/.png files into
sample_case/photos/ and .wav/.mp3 files into sample_case/audio/ to exercise
the face-clustering and transcription pipelines end-to-end; everything else
(contacts, calls, messages, timeline, graph, anomaly detection) works with
just the generated CSV/JSON files.

Usage:
    python scripts/seed_demo_case.py
"""

import csv
import json
from datetime import datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CASE_DIR = ROOT / "sample_case"

CONTACTS = [
    ("Alice Rao", "+91-98100-11111"),
    ("Bob Mehta", "+91-98100-22222"),
    ("Priya Nair", "+91-98100-33333"),
    ("Unknown Caller", "+91-70000-99999"),
]

BASE_DAY = datetime(2026, 3, 10, 8, 0, 0)


def write_contacts():
    with (CASE_DIR / "contacts.csv").open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["name", "phone_number"])
        writer.writerows(CONTACTS)


def write_calls():
    rows = [
        ("number", "direction", "duration_seconds", "timestamp"),
        (CONTACTS[0][1], "outgoing", 180, (BASE_DAY + timedelta(hours=1)).isoformat()),
        (CONTACTS[1][1], "incoming", 45, (BASE_DAY + timedelta(hours=2)).isoformat()),
        (CONTACTS[3][1], "missed", 0, (BASE_DAY + timedelta(hours=3)).isoformat()),
        # Deliberate anomaly: a call at 03:20 local device time.
        (CONTACTS[3][1], "outgoing", 640, (BASE_DAY + timedelta(hours=19, minutes=20)).isoformat()),
    ]
    with (CASE_DIR / "calls.csv").open("w", newline="", encoding="utf-8") as fh:
        csv.writer(fh).writerows(rows)


def write_messages():
    rows = [
        ("sender", "recipient", "body", "timestamp", "app"),
        (
            "device_owner",
            CONTACTS[0][1],
            "Are we still meeting about the transfer tonight?",
            (BASE_DAY + timedelta(hours=1, minutes=5)).isoformat(),
            "sms",
        ),
        (
            CONTACTS[0][1],
            "device_owner",
            "Yes, usual place. Bring the money.",
            (BASE_DAY + timedelta(hours=1, minutes=8)).isoformat(),
            "whatsapp",
        ),
        (
            "device_owner",
            CONTACTS[2][1],
            "Can you send the documents we discussed?",
            (BASE_DAY + timedelta(hours=4)).isoformat(),
            "whatsapp",
        ),
    ]
    with (CASE_DIR / "messages.csv").open("w", newline="", encoding="utf-8") as fh:
        csv.writer(fh).writerows(rows)


def write_device_events():
    events = [
        {
            "type": "app_install",
            "timestamp": (BASE_DAY + timedelta(hours=5)).isoformat(),
            "detail": "SecureVault (hidden storage app)",
        },
        {
            "type": "app_uninstall",
            "timestamp": (BASE_DAY + timedelta(hours=6, minutes=10)).isoformat(),
            "detail": "SecureVault (hidden storage app)",
        },
        {
            "type": "file_deleted",
            "timestamp": (BASE_DAY + timedelta(hours=5, minutes=30)).isoformat(),
            "detail": "IMG_4471.jpg deleted from DCIM",
            "file_name": "IMG_4471.jpg",
        },
        {
            "type": "file_recovered",
            "timestamp": (BASE_DAY + timedelta(hours=7)).isoformat(),
            "detail": "IMG_4471.jpg recovered from unallocated space",
            "file_name": "IMG_4471.jpg",
        },
    ]
    (CASE_DIR / "device_events.json").write_text(json.dumps(events, indent=2), encoding="utf-8")


def write_readme():
    (CASE_DIR / "README.md").write_text(
        "# Sample Case\n\n"
        "Synthetic demo data generated by `scripts/seed_demo_case.py`. Contacts, calls,\n"
        "messages and device events are fully synthetic and safe to demo publicly.\n\n"
        "`photos/` and `audio/` are intentionally empty — drop your own image/audio files\n"
        "in to exercise face clustering and transcription. Everything else (timeline,\n"
        "relationship graph, anomaly detection, reporting) works from the CSV/JSON alone.\n\n"
        "Ingest this case via the API:\n\n"
        "```\n"
        "POST /cases            {\"name\": \"Sample Case\", \"source_path\": \"<absolute path to this folder>\"}\n"
        "POST /cases/{id}/ingest\n"
        "```\n",
        encoding="utf-8",
    )


def main():
    CASE_DIR.mkdir(exist_ok=True)
    (CASE_DIR / "photos").mkdir(exist_ok=True)
    (CASE_DIR / "audio").mkdir(exist_ok=True)

    write_contacts()
    write_calls()
    write_messages()
    write_device_events()
    write_readme()

    print(f"Sample case written to {CASE_DIR}")


if __name__ == "__main__":
    main()
